### ISSUE TITLE
Installation fails (server jamesporter.me is down)

### ISSUE THREAD

**Issue by Alexander-Barth** [JuliaWeb/Gumbo.jl#54]
The installation for Gumbo.jl currently fails on travis CI because the server jamesporter.me is down.
https://travis-ci.org/gher-ulg/PhysOcean.jl/jobs/413749067#L498

Thank you for your help and this very useful package!

**Comment by porterjamesj** [comment]
Whoops, sorry about that! Not sure how my site was down, restarted nginx and all appears to be well.

Also, I'm going to be cutting a release soon that makes it so the build doesn't involve my personal site anymore, and instead uses some much better Julia shared infrastructure for distributing binary dependencies.
