### ISSUE TITLE
Maintainership

### ISSUE THREAD

**Issue by porterjamesj** [JuliaWeb/Gumbo.jl#83]
Hi all,

I'm the original author of this package, but as is probably obvious to those of you who use it heavily, I don't really have the bandwidth or interest to maintain it anymore.

In practice, maintenance has been done by an ad-hoc group of JuliaWeb organization members for a while now. I'm opening this issue mostly to acknowledge this, formally hand-off maintenance, and so those interested can have a quick conversation to settle on a person or group of people who are going to maintain this package going forward.

cc'ing a few people who I feel like should be involved or might be interested in the outcome: @aviks @pfitzseb @essenciary

**Comment by aviks** [comment]
I don't have much time to work on this package, but I'm happy to review PRs and keep things ticking along, since this is a dependency of some of my packages. This repo is already in an org, with wide membership, so I don't think anything specific needs to be done for now.

**Comment by pfitzseb** [comment]
I'd also be happy to review PRs and fix the occasional bug :)

**Comment by porterjamesj** [comment]
Great, thanks all! Just wanted to make sure to let folks know before I unsubscribed from notifications.
