### ISSUE TITLE
ERROR: MethodError: no method matching tag(::HTMLText)

### ISSUE THREAD

**Issue by programistawpf** [JuliaWeb/Gumbo.jl#88]
'''
julia> url="http://rp.pl"
"http://rp.pl"

julia> doc=parsehtml(String(read(download(url))));

julia> for elem in PreOrderDFS(doc.root) println(tag(elem)) end
HTML
head
script
ERROR: MethodError: no method matching tag(::HTMLText)
Closest candidates are:
  tag(::HTMLElement{T}) where T at C:\Users\PC\.julia\packages\Gumbo\OhZJu\src\manipulation.jl:6
Stacktrace:
 [1] top-level scope at .\REPL[86]:1 [inlined]
 [2] top-level scope at .\none:0

'''
Thx, Paul

**Comment by aviks** [comment]
Text nodes don't have a tag. So this is as expected, I think.

**Comment by programistawpf** [comment]
> 
> 
> Text nodes don't have a tag. So this is as expected, I think.

expected but Julia is stoped... What now ?
