### ISSUE TITLE
Not working in Alpine Linux or julia musl.

### ISSUE THREAD

**Issue by abcfy2** [JuliaWeb/Gumbo.jl#89]
Hi there.

I use this in Alpine Linux, but I got this error:

```jl
julia> parsehtml("<h1> Hello, world! </h1>")
ERROR: could not load library "libgumbo.so.1"
Error loading shared library libgumbo.so.1: No such file or directory
Stacktrace:
 [1] parsehtml(input::String; strict::Bool, preserve_whitespace::Bool)
   @ Gumbo ~/.julia/packages/Gumbo/aBmWO/src/conversion.jl:4
 [2] parsehtml(input::String)
   @ Gumbo ~/.julia/packages/Gumbo/aBmWO/src/conversion.jl:4
 [3] top-level scope
   @ REPL[7]:1

julia>
```

What's wrong ? How could I use it in Alpine Linux?

**Comment by aviks** [comment]
We do build Gumbo binaries for musl as you can see here: https://github.com/JuliaBinaryWrappers/Gumbo_jll.jl/blob/master/Artifacts.toml

So I'm not really sure what could be wrong here.

**Comment by aviks** [comment]
Thanks to the Yggdrasil maintainers, the fix is in https://github.com/JuliaPackaging/Yggdrasil/pull/3929 . Once the package [is registered](https://github.com/JuliaRegistries/General/pull/49187) this should be fixed.

**Comment by abcfy2** [comment]
Great. It's working now. Thank you.
