### ISSUE TITLE
ERROR: UndefVarError: libgumbo not defined macbook m1

### ISSUE THREAD

**Issue by AbhimanyuAryan** [JuliaWeb/Gumbo.jl#90]
This is when I run `Gumbo v0.8.0` on `v"1.6.2"` on intel mac

```
julia> doc = parsehtml(read("index.html", String))
HTML Document:
<!DOCTYPE html>
```
when running `Gumbo v0.8.0` on mac m1 1.7.0 

```
julia> doc = parsehtml(read("index.html", String))
ERROR: UndefVarError: libgumbo not defined
Stacktrace:
 [1] parsehtml(input::String; strict::Bool, preserve_whitespace::Bool)
   @ Gumbo ~/.julia/packages/Gumbo/aBmWO/src/conversion.jl:4
 [2] parsehtml(input::String)
   @ Gumbo ~/.julia/packages/Gumbo/aBmWO/src/conversion.jl:4
 [3] top-level scope
   @ REPL[3]:1
```

**Comment by aviks** [comment]
The Gumbo jll is not compiled for this architecture. The [yggdrasil build](https://github.com/JuliaPackaging/Yggdrasil/blob/master/G/Gumbo/build_tarballs.jl) needs to be redone with the m1. I'll probably get to this at some point, but can't promise when. This is not high priority for me, sorry. I don't have access to this hardware. If someone gets to this before me, that'd be great.

**Comment by AbhimanyuAryan** [comment]
@aviks I can compile it for M1 arch if that's ok?

**Comment by giordano** [comment]
With latest `Gumbo_jll` (and without having to change anything else in this package, #91 isn't needed at all and I don't see its point), tests of this package pass for me:
```
     Testing Running tests...
Test Summary: | Pass  Total  Time
test = 30     |    1      1  0.1s
Test Summary:    | Pass  Total  Time
test = multitext |    1      1  0.0s
Test Summary: | Pass  Total  Time
test = varied |    1      1  0.2s
Test Summary:     | Pass  Total  Time
test = whitespace |    1      1  0.1s
Test Summary: | Pass  Total  Time
xml entities  |    1      1  0.0s
     Testing Gumbo tests passed
```

**Comment by aviks** [comment]
Thanks @giordano  and @AbhimanyuAryan.   Closed by https://github.com/JuliaPackaging/Yggdrasil/pull/4149
