### ISSUE TITLE
Google's Gumbo Parser officially archived

### ISSUE THREAD

**Issue by algunion** [JuliaWeb/Gumbo.jl#97]
Hello,

I love what you did with this package. 

Google's Gumbo Parser was archived on 16 February - will this affect this project? 

Is there a roadmap of where this repository is going?

P. S. I am using this project in my work and am willing to contribute/help.

**Comment by aviks** [comment]
I mean, at this point, we host the binary, and this wrapper is pretty feature complete. So no immediate effect. If there are major security issues found in Gumbo, we can reconsider.
